---
name: debian-{system.release}-{system.architecture}-{%y}{%m}{%d}
provider:
  name: azure
  waagent:
    version: 2.0.14
bootstrapper:
  mirror: http://deb.debian.org/debian/
  workspace: /target
system:
  release: wheezy
  architecture: amd64
  bootloader: grub
  charmap: UTF-8
  locale: en_US
  timezone: UTC
volume:
  backing: vhd
  partitions:
    type: msdos
    root:
      filesystem: ext4
      size: 10GiB
packages:
  components:
    - main
    - contrib
    - non-free
  preferences:
    backport-kernel:
      - package: linux-image-* initramfs-tools
        pin: release n=wheezy-backports
        pin-priority: 500
plugins:
  ntp:
    servers:
      - time.windows.com
