---
name: disk
provider:
  name: gce
  description: Debian {system.release} {system.architecture}
bootstrapper:
  workspace: /target
system:
  release: wheezy
  architecture: amd64
  bootloader: grub
  charmap: UTF-8
  locale: en_US
  timezone: UTC
volume:
  backing: raw
  partitions:
    type: msdos
    root:
      filesystem: ext4
      size: 10GiB
packages:
  sources:
    google-cloud:
      - deb http://packages.cloud.google.com/apt cloud-sdk-{system.release} main
      - deb http://packages.cloud.google.com/apt google-cloud-compute-legacy-{system.release} main
  install:
    - google-cloud-sdk
    - google-compute-daemon
    - google-startup-scripts
    - python-gcimagebundle
    - rsync
    - screen
    - vim
plugins:
  google_cloud_repo:
    cleanup_bootstrap_key: true
    enable_keyring_repo: true
  ntp:
    servers:
      - metadata.google.internal
