---
name: debian-{system.release}-{system.architecture}:latest
provider:
  name: docker
  labels:
    summary: Debian {system.release} {system.architecture}
    description: >-
      Minimized version of Debian jessie
      without any manpages, additional documentation
      or other language files.
      Additional package installs:
      inetutils-ping (dep: netbase) and iproute2
    distribution-scope: public
  dockerfile:
    - CMD /bin/bash
bootstrapper:
  workspace: /target
  variant: minbase
system:
  release: jessie
  architecture: amd64
  bootloader: none
  charmap: UTF-8
  locale: en_US
  timezone: UTC
packages:
  install:
    - inetutils-ping
    - iproute2
volume:
  backing: folder
  partitions:
    type: none
    root:
      filesystem: ext4
      size: 1GiB
plugins:
  minimize_size:
    apt:
      autoclean: true
      languages: [none]
      gzip_indexes: true
      autoremove_suggests: true
    dpkg:
      locales: []
      exclude_docs: true
